### ISSUE TITLE
Jest 27

### ISSUE THREAD

**Issue by nicolaspayot** [remos/jest-file-loader#8]
Hello !

It seems the transformer API changed with Jest 27, as mentionned in this pull request: https://github.com/facebook/jest/pull/10834/files.

Indeed, the `process` function now takes an options object as last parameter rather than separate config and other options.

Here's the fix :  
```javascript
process(src, filename, options) {
    const exportedPath = JSON.stringify(slash(path.relative(options.config.rootDir, filename)));
    ...
}
```
I'd gladly open a pull request to fix it.

**Comment by remos** [comment]
Hi @nicolaspayot,

Absolutely, that'd be great. Thanks for pointing that out too!
